# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A_B test example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A_B test example

pod 'Firebase/RemoteConfig'
pod 'Firebase/Analytics'

end
